export interface IndustrySubcategory {
  category: string;
  subcategory: string;
  /** 拼接后的完整 tag，如 "餐饮服务_中餐馆" */
  tag: string;
}

export const INDUSTRY_SUBCATEGORIES: IndustrySubcategory[] = [
  { category: '餐饮服务', subcategory: '中餐馆', tag: '餐饮服务_中餐馆' },
  { category: '餐饮服务', subcategory: '火锅店', tag: '餐饮服务_火锅店' },
  { category: '餐饮服务', subcategory: '烧烤店', tag: '餐饮服务_烧烤店' },
  { category: '餐饮服务', subcategory: '奶茶店', tag: '餐饮服务_奶茶店' },
  { category: '餐饮服务', subcategory: '咖啡店', tag: '餐饮服务_咖啡店' },
  { category: '餐饮服务', subcategory: '烘焙店', tag: '餐饮服务_烘焙店' },
  { category: '餐饮服务', subcategory: '快餐店', tag: '餐饮服务_快餐店' },
  { category: '酒店民宿', subcategory: '商务酒店', tag: '酒店民宿_商务酒店' },
  { category: '酒店民宿', subcategory: '度假酒店', tag: '酒店民宿_度假酒店' },
  { category: '酒店民宿', subcategory: '精品民宿', tag: '酒店民宿_精品民宿' },
  { category: '酒店民宿', subcategory: '城市民宿', tag: '酒店民宿_城市民宿' },
  { category: '酒店民宿', subcategory: '客栈', tag: '酒店民宿_客栈' },
  { category: '美业健康', subcategory: '美容院', tag: '美业健康_美容院' },
  { category: '美业健康', subcategory: '美甲店', tag: '美业健康_美甲店' },
  { category: '美业健康', subcategory: '美发店', tag: '美业健康_美发店' },
  { category: '美业健康', subcategory: '轻医美机构', tag: '美业健康_轻医美机构' },
  { category: '美业健康', subcategory: '皮肤管理', tag: '美业健康_皮肤管理' },
  { category: '美业健康', subcategory: '养生馆', tag: '美业健康_养生馆' },
  { category: '美业健康', subcategory: '理疗馆', tag: '美业健康_理疗馆' },
  { category: '教育培训', subcategory: '职业教育', tag: '教育培训_职业教育' },
  { category: '教育培训', subcategory: '语言培训', tag: '教育培训_语言培训' },
  { category: '教育培训', subcategory: '考研培训', tag: '教育培训_考研培训' },
  { category: '教育培训', subcategory: '艺术培训', tag: '教育培训_艺术培训' },
  { category: '教育培训', subcategory: '少儿素质教育', tag: '教育培训_少儿素质教育' },
  { category: '教育培训', subcategory: '成人技能培训', tag: '教育培训_成人技能培训' },
  { category: '汽车服务', subcategory: '二手车门店', tag: '汽车服务_二手车门店' },
  { category: '汽车服务', subcategory: '新车经销', tag: '汽车服务_新车经销' },
  { category: '汽车服务', subcategory: '汽车美容', tag: '汽车服务_汽车美容' },
  { category: '汽车服务', subcategory: '汽车维修', tag: '汽车服务_汽车维修' },
  { category: '汽车服务', subcategory: '汽车改装', tag: '汽车服务_汽车改装' },
  { category: '汽车服务', subcategory: '汽车租赁', tag: '汽车服务_汽车租赁' },
  { category: '家居装修', subcategory: '装修公司', tag: '家居装修_装修公司' },
  { category: '家居装修', subcategory: '全屋定制', tag: '家居装修_全屋定制' },
  { category: '家居装修', subcategory: '家居建材', tag: '家居装修_家居建材' },
  { category: '家居装修', subcategory: '家电门店', tag: '家居装修_家电门店' },
  { category: '家居装修', subcategory: '智能家居', tag: '家居装修_智能家居' },
  { category: '家居装修', subcategory: '软装设计', tag: '家居装修_软装设计' },
  { category: '本地零售', subcategory: '生鲜门店', tag: '本地零售_生鲜门店' },
  { category: '本地零售', subcategory: '社区超市', tag: '本地零售_社区超市' },
  { category: '本地零售', subcategory: '母婴门店', tag: '本地零售_母婴门店' },
  { category: '本地零售', subcategory: '宠物门店', tag: '本地零售_宠物门店' },
  { category: '本地零售', subcategory: '烟酒店', tag: '本地零售_烟酒店' },
  { category: '本地零售', subcategory: '药店', tag: '本地零售_药店' },
  { category: '生活服务', subcategory: '家政服务', tag: '生活服务_家政服务' },
  { category: '生活服务', subcategory: '搬家服务', tag: '生活服务_搬家服务' },
  { category: '生活服务', subcategory: '洗衣洗护', tag: '生活服务_洗衣洗护' },
  { category: '生活服务', subcategory: '开锁服务', tag: '生活服务_开锁服务' },
  { category: '生活服务', subcategory: '管道维修', tag: '生活服务_管道维修' },
  { category: '生活服务', subcategory: '家电清洗', tag: '生活服务_家电清洗' },
  { category: '医疗健康', subcategory: '口腔门诊', tag: '医疗健康_口腔门诊' },
  { category: '医疗健康', subcategory: '眼科门诊', tag: '医疗健康_眼科门诊' },
  { category: '医疗健康', subcategory: '体检中心', tag: '医疗健康_体检中心' },
  { category: '医疗健康', subcategory: '康复中心', tag: '医疗健康_康复中心' },
  { category: '医疗健康', subcategory: '中医诊所', tag: '医疗健康_中医诊所' },
  { category: '医疗健康', subcategory: '心理咨询', tag: '医疗健康_心理咨询' },
  { category: '企业服务', subcategory: '财税服务', tag: '企业服务_财税服务' },
  { category: '企业服务', subcategory: '法律服务', tag: '企业服务_法律服务' },
  { category: '企业服务', subcategory: '人力资源', tag: '企业服务_人力资源' },
  { category: '企业服务', subcategory: '软件服务', tag: '企业服务_软件服务' },
  { category: '企业服务', subcategory: '知识产权', tag: '企业服务_知识产权' },
  { category: '企业服务', subcategory: '咨询服务', tag: '企业服务_咨询服务' },
  { category: '文旅休闲', subcategory: '景区乐园', tag: '文旅休闲_景区乐园' },
  { category: '文旅休闲', subcategory: '旅行社', tag: '文旅休闲_旅行社' },
  { category: '文旅休闲', subcategory: '露营基地', tag: '文旅休闲_露营基地' },
  { category: '文旅休闲', subcategory: '健身房', tag: '文旅休闲_健身房' },
  { category: '文旅休闲', subcategory: '瑜伽馆', tag: '文旅休闲_瑜伽馆' },
  { category: '文旅休闲', subcategory: '影城剧场', tag: '文旅休闲_影城剧场' },
  { category: '电商出海', subcategory: '跨境电商', tag: '电商出海_跨境电商' },
  { category: '电商出海', subcategory: '外贸工厂', tag: '电商出海_外贸工厂' },
  { category: '电商出海', subcategory: '独立站运营', tag: '电商出海_独立站运营' },
  { category: '电商出海', subcategory: '海外仓服务', tag: '电商出海_海外仓服务' },
  { category: '电商出海', subcategory: '国际物流', tag: '电商出海_国际物流' },
  { category: '建筑行业', subcategory: '门楼', tag: '建筑行业_门楼' },
];

export const INDUSTRY_CATEGORIES = [...new Set(INDUSTRY_SUBCATEGORIES.map((item) => item.category))];
