import type { DecisionContext } from './types.js';

export const realisticScenarios: Array<{ name: string; input: DecisionContext }> = [
  {
    name: 'Dental clinic content acquisition sprint',
    input: {
      missionId: 'mis_dental_001',
      missionType: 'content_production',
      riskLevel: 'L2',
      latencyPriority: 'normal',
      revenueImpact: 'high',
      evidenceSufficiency: 'medium',
      requiresExternalAction: true,
      recentFailureCount: 0,
      tags: ['douyin', 'healthcare', 'campaign'],
    },
  },
  {
    name: 'Hot comment surge with warm high-value leads',
    input: {
      missionId: 'mis_hot_002',
      missionType: 'interaction_handling',
      riskLevel: 'L2',
      latencyPriority: 'urgent',
      revenueImpact: 'strategic',
      evidenceSufficiency: 'high',
      hasWarmLead: true,
      requiresHumanTouchpoint: false,
      recentFailureCount: 0,
      tags: ['comment-burst', 'warm-leads'],
    },
  },
  {
    name: 'Follow-up pipeline under external instability',
    input: {
      missionId: 'mis_followup_003',
      missionType: 'conversion_push',
      riskLevel: 'L3',
      latencyPriority: 'high',
      revenueImpact: 'high',
      evidenceSufficiency: 'low',
      requiresHumanTouchpoint: true,
      externalDependencyUnstable: true,
      recentFailureCount: 2,
      budgetCap: 5,
      tags: ['voice-call', 'critical-lead'],
    },
  },
];

export const simulationMissionBatch: DecisionContext[] = [
  {
    missionId: 'sim_001',
    missionType: 'signal_scan',
    riskLevel: 'L1',
    latencyPriority: 'normal',
    revenueImpact: 'medium',
    evidenceSufficiency: 'medium',
    tags: ['industry-scan', 'douyin'],
  },
  {
    missionId: 'sim_002',
    missionType: 'strategy_design',
    riskLevel: 'L1',
    latencyPriority: 'normal',
    revenueImpact: 'high',
    evidenceSufficiency: 'high',
    tags: ['playbook', 'launch'],
  },
  {
    missionId: 'sim_003',
    missionType: 'content_production',
    riskLevel: 'L2',
    latencyPriority: 'normal',
    revenueImpact: 'high',
    evidenceSufficiency: 'medium',
    requiresExternalAction: true,
    tags: ['video', 'publish'],
  },
  {
    missionId: 'sim_004',
    missionType: 'interaction_handling',
    riskLevel: 'L2',
    latencyPriority: 'urgent',
    revenueImpact: 'strategic',
    evidenceSufficiency: 'high',
    hasWarmLead: true,
    tags: ['comment-burst', 'private-message'],
  },
  {
    missionId: 'sim_005',
    missionType: 'lead_qualification',
    riskLevel: 'L1',
    latencyPriority: 'high',
    revenueImpact: 'high',
    evidenceSufficiency: 'high',
    hasWarmLead: true,
    tags: ['lead-tiers'],
  },
  {
    missionId: 'sim_006',
    missionType: 'conversion_push',
    riskLevel: 'L2',
    latencyPriority: 'high',
    revenueImpact: 'high',
    evidenceSufficiency: 'medium',
    requiresHumanTouchpoint: true,
    tags: ['appointment', 'followup'],
  },
  {
    missionId: 'sim_007',
    missionType: 'conversion_push',
    riskLevel: 'L3',
    latencyPriority: 'urgent',
    revenueImpact: 'strategic',
    evidenceSufficiency: 'low',
    requiresHumanTouchpoint: true,
    externalDependencyUnstable: true,
    recentFailureCount: 2,
    budgetCap: 5,
    tags: ['critical-lead', 'voice'],
  },
  {
    missionId: 'sim_008',
    missionType: 'recovery_replay',
    riskLevel: 'L2',
    latencyPriority: 'high',
    revenueImpact: 'medium',
    evidenceSufficiency: 'high',
    recentFailureCount: 3,
    tags: ['repair', 'workflow'],
  },
  {
    missionId: 'sim_009',
    missionType: 'review_evolution',
    riskLevel: 'L1',
    latencyPriority: 'low',
    revenueImpact: 'strategic',
    evidenceSufficiency: 'high',
    tags: ['feedback', 'playbook'],
  },
  {
    missionId: 'sim_010',
    missionType: 'content_production',
    riskLevel: 'L3',
    latencyPriority: 'urgent',
    revenueImpact: 'high',
    evidenceSufficiency: 'low',
    requiresExternalAction: true,
    recentFailureCount: 1,
    tags: ['sensitive', 'publish'],
  },
];
